In [61]:
import pandas as pd

pd.set_option('display.max_columns',50)

imp=pd.read_csv('Import.csv',sep=";",index_col=False,skip_blank_lines=True,quotechar='"',doublequote=True,on_bad_lines="skip")
exp=pd.read_csv('Export.csv',sep=";",index_col=False,skip_blank_lines=True,quotechar='"',doublequote=True,on_bad_lines="skip")
display(imp,exp)

,Code du chapitre SH,Libellé du chapitre SH,Code du produit SH,Libellé du produit SH,Code du groupement d'utilisation,Libellé du groupement d'utilisation,Code du nouveau produits remarquables,Libellé du nouveau produits remarquables,Code de la section CTCI,Libellé de la section CTCI,Code de la division CTCI,Libellé de la division CTCI,Code du groupe CTCI,Libellé du groupe CTCI,Continent,Code du pays,Libellé du pays,Code du flux,Libellé du flux,Année,Mois,Poids en KG,Valeur DHS,Unité complementaire
0,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8701101100,"TRACTEURS A ESSIEU SIMPLE EN C.K.D, A MOTEUR A...",6,PRODUITS FINIS D'EQUIPEMENT AGRICOLE,603,MOTOCULTEURS ET TRACTEURS AGRICOLES,7,MACHINES ET MATÉRIEL DE TRANSPORT,72,MACHINES SPÉCIALISÉES À USAGE PARTICULIER,722,TRACTEURS (AUTRES QUE CEUX DES POSITIONS 744.1...,EUROPE,DE,ALLEMAGNE,14,Importations CAF,2024,5,100,5000,1
1,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8701101100,"TRACTEURS A ESSIEU SIMPLE EN C.K.D, A MOTEUR A...",6,PRODUITS FINIS D'EQUIPEMENT AGRICOLE,603,MOTOCULTEURS ET TRACTEURS AGRICOLES,7,MACHINES ET MATÉRIEL DE TRANSPORT,72,MACHINES SPÉCIALISÉES À USAGE PARTICULIER,722,TRACTEURS (AUTRES QUE CEUX DES POSITIONS 744.1...,EUROPE,ES,ESPAGNE,14,Importations CAF,2022,2,100,5000,0
2,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8701101100,"TRACTEURS A ESSIEU SIMPLE EN C.K.D, A MOTEUR A...",6,PRODUITS FINIS D'EQUIPEMENT AGRICOLE,603,MOTOCULTEURS ET TRACTEURS AGRICOLES,7,MACHINES ET MATÉRIEL DE TRANSPORT,72,MACHINES SPÉCIALISÉES À USAGE PARTICULIER,722,TRACTEURS (AUTRES QUE CEUX DES POSITIONS 744.1...,ASIE,JP,JAPON,14,Importations CAF,2025,1,80,5000,1
3,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8701101100,"TRACTEURS A ESSIEU SIMPLE EN C.K.D, A MOTEUR A...",6,PRODUITS FINIS D'EQUIPEMENT AGRICOLE,603,MOTOCULTEURS ET TRACTEURS AGRICOLES,7,MACHINES ET MATÉRIEL DE TRANSPORT,72,MACHINES SPÉCIALISÉES À USAGE PARTICULIER,722,TRACTEURS (AUTRES QUE CEUX DES POSITIONS 744.1...,EUROPE,BE,BELGIQUE,14,Importations CAF,2023,8,200,2500,1
4,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8701101100,"TRACTEURS A ESSIEU SIMPLE EN C.K.D, A MOTEUR A...",6,PRODUITS FINIS D'EQUIPEMENT AGRICOLE,603,MOTOCULTEURS ET TRACTEURS AGRICOLES,7,MACHINES ET MATÉRIEL DE TRANSPORT,72,MACHINES SPÉCIALISÉES À USAGE PARTICULIER,722,TRACTEURS (AUTRES QUE CEUX DES POSITIONS 744.1...,EUROPE,ES,ESPAGNE,14,Importations CAF,2022,11,60,2400,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64423,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8716909000,AUTRES PARTIES POUR REMORQUES N.AUTOMOBILES,7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,760,PARTIES ET PIECES DETACHEES POUR VEHICULES IND...,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),786,REMORQUES ET SEMI-REMORQUES. AUTRES VÉHICULES ...,EUROPE,TR,TURQUIE,14,Importations CAF,2023,7,"244687,701",7762554,0
64424,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8716909000,AUTRES PARTIES POUR REMORQUES N.AUTOMOBILES,7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,760,PARTIES ET PIECES DETACHEES POUR VEHICULES IND...,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),786,REMORQUES ET SEMI-REMORQUES. AUTRES VÉHICULES ...,EUROPE,TR,TURQUIE,14,Importations CAF,2023,9,44280,1461240,0
64425,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8716909000,AUTRES PARTIES POUR REMORQUES N.AUTOMOBILES,7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,760,PARTIES ET PIECES DETACHEES POUR VEHICULES IND...,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),786,REMORQUES ET SEMI-REMORQUES. AUTRES VÉHICULES ...,EUROPE,TR,TURQUIE,14,Importations CAF,2024,1,"194959,72",6300951,0
64426,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8716909000,AUTRES PARTIES POUR REMORQUES N.AUTOMOBILES,7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,760,PARTIES ET PIECES DETACHEES POUR VEHICULES IND...,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),786,REMORQUES ET SEMI-REMORQUES. AUTRES VÉHICULES ...,EUROPE,TR,TURQUIE,14,Importations CAF,2024,7,"22262,04",555170,0
64427,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8716909000,AUTRES PARTIES POUR REMORQUES N.AUTOMOBILES,7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,760,PARTIES ET PIECES DETACHEES POUR VEHICULES IND...,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),786,REMORQUES ET SEMI-REMORQUES. AUTRES VÉHICULES ...,EUROPE,TR,TURQUIE,14,Importations CAF,2025,9,"132535,821","4227354,001",0

,Code du chapitre SH,Libellé du chapitre SH,Code du produit SH,Libellé du produit SH,Code du groupement d'utilisation,Libellé du groupement d'utilisation,Code du nouveau produits remarquables,Libellé du nouveau produits remarquables,Code de la section CTCI,Libellé de la section CTCI,Code de la division CTCI,Libellé de la division CTCI,Code du groupe CTCI,Libellé du groupe CTCI,Continent,Code du pays,Libellé du pays,Code du flux,Libellé du flux,Année,Mois,Poids en KG,Valeur DHS,Unité complementaire
0,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8701219100,"TRACTEURS ROUTIERS NEUFS POUR SEMI-REMORQUES, ...",7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,769,TRACTEURS SAUF AGRICOLES,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),783,"VÉHICULES ROUTIERS AUTOMOBILES, N.D.A.",AFRIQUE,CD,LA REPUBLIQUE DEMOCRATIQUE DU CONGO,24,Exportations FAB,2023,6,8072,1114943,1
1,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8701109180,"MOTOCULTEURS USAGES, A MOTEUR A EXPLOSION OU A...",6,PRODUITS FINIS D'EQUIPEMENT AGRICOLE,603,MOTOCULTEURS ET TRACTEURS AGRICOLES,7,MACHINES ET MATÉRIEL DE TRANSPORT,72,MACHINES SPÉCIALISÉES À USAGE PARTICULIER,722,TRACTEURS (AUTRES QUE CEUX DES POSITIONS 744.1...,AFRIQUE,SN,SENEGAL,24,Exportations FAB,2022,11,42000,984500,6
2,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8701109180,"MOTOCULTEURS USAGES, A MOTEUR A EXPLOSION OU A...",6,PRODUITS FINIS D'EQUIPEMENT AGRICOLE,603,MOTOCULTEURS ET TRACTEURS AGRICOLES,7,MACHINES ET MATÉRIEL DE TRANSPORT,72,MACHINES SPÉCIALISÉES À USAGE PARTICULIER,722,TRACTEURS (AUTRES QUE CEUX DES POSITIONS 744.1...,AFRIQUE,MR,MAURITANIE,24,Exportations FAB,2024,10,3060,80000,1
3,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8701109180,"MOTOCULTEURS USAGES, A MOTEUR A EXPLOSION OU A...",6,PRODUITS FINIS D'EQUIPEMENT AGRICOLE,603,MOTOCULTEURS ET TRACTEURS AGRICOLES,7,MACHINES ET MATÉRIEL DE TRANSPORT,72,MACHINES SPÉCIALISÉES À USAGE PARTICULIER,722,TRACTEURS (AUTRES QUE CEUX DES POSITIONS 744.1...,AFRIQUE,MR,MAURITANIE,24,Exportations FAB,2023,10,9640,240000,2
4,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8701299900,AUTRES TRACTEURS ROUTIERS USAGES POUR SEMI-REM...,7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,769,TRACTEURS SAUF AGRICOLES,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),783,"VÉHICULES ROUTIERS AUTOMOBILES, N.D.A.",AFRIQUE,EG,EGYPTE,24,Exportations FAB,2024,10,2000,35000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12816,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8716909000,AUTRES PARTIES POUR REMORQUES N.AUTOMOBILES,7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,760,PARTIES ET PIECES DETACHEES POUR VEHICULES IND...,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),786,REMORQUES ET SEMI-REMORQUES. AUTRES VÉHICULES ...,EUROPE,TR,TURQUIE,24,Exportations FAB,2024,12,"23,8",2265,0
12817,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8716909000,AUTRES PARTIES POUR REMORQUES N.AUTOMOBILES,7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,760,PARTIES ET PIECES DETACHEES POUR VEHICULES IND...,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),786,REMORQUES ET SEMI-REMORQUES. AUTRES VÉHICULES ...,EUROPE,RU,FEDERATION DE RUSSIE,24,Exportations FAB,2024,8,359,18897,0
12818,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8716909000,AUTRES PARTIES POUR REMORQUES N.AUTOMOBILES,7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,760,PARTIES ET PIECES DETACHEES POUR VEHICULES IND...,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),786,REMORQUES ET SEMI-REMORQUES. AUTRES VÉHICULES ...,EUROPE,RO,ROUMANIE,24,Exportations FAB,2024,6,137,13925,0
12819,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8716909000,AUTRES PARTIES POUR REMORQUES N.AUTOMOBILES,7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,760,PARTIES ET PIECES DETACHEES POUR VEHICULES IND...,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),786,REMORQUES ET SEMI-REMORQUES. AUTRES VÉHICULES ...,EUROPE,PT,PORTUGAL,24,Exportations FAB,2024,6,9850,44157,0
12820,87,"AUTOMOBILES, TRACTEURS, CYCLES, VÉHICULES TERR...",8716909000,AUTRES PARTIES POUR REMORQUES N.AUTOMOBILES,7,PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL,760,PARTIES ET PIECES DETACHEES POUR VEHICULES IND...,7,MACHINES ET MATÉRIEL DE TRANSPORT,78,VÉHICULES ROUTIERS (MÊME À COUSSIN D¿AIR),786,REMORQUES ET SEMI-REMORQUES. AUTRES VÉHICULES ...,EUROPE,RU,FEDERATION DE RUSSIE,24,Exportations FAB,2025,8,555,18931,0

# EDA Phase

we need to explore our data first,